version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    environment:
      IMAGE_NAME: relovely/relovely-api
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  deploy:
    docker:
      - image: circleci/node:12.14.1
    steps:
    - run: |
      if [ "$CIRCLE_BRANCH" = "develop" ]; then
        CURRENT_DROPLET_IP=$DEVELOPMENT_DROPLET_IP
      elif [ "$CIRCLE_BRANCH" = "master" ]; then
        CURRENT_DROPLET_IP=$DROPLET_IP
      echo "export CURRENT_DROPLET_IP=$CURRENT_DROPLET_IP" >> $BASH_ENV
    - run:
      name: Deploy Container
      command: |
        ssh -o StrictHostKeyChecking=no root@$CURRENT_DROPLET_IP bash -c '
        cat ~/password.txt | docker login --username relovely --password-stdin;
        docker stop $(docker ps -a -q);
        docker rm -f $(docker ps -a -q);
        docker rmi -f $(docker images -q);
        docker pull relovely/relovely-api:latest;
        docker run --env-file ~/env.config -d --network host relovely/relovely-api'
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master

