version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: relovely/relovely-api
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: Deploy Container
          command: |
            ssh -o StrictHostKeyChecking=no circleci@192.34.56.220 bash -c '
            cd /home/circleci/deploy;
            ./deploy.sh'
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
