version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    environment:
      IMAGE_NAME: relovely/relovely-api
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set IP
          command: |
            if [ $CIRCLE_BRANCH = 'develop' ]; then
              CURRENT_DROPLET_IP=$DEVELOPMENT_DROPLET_IP
            elif [ $CIRCLE_BRANCH = 'master' ]; then
              CURRENT_DROPLET_IP=$DROPLET_IP
            fi
            echo "export CURRENT_DROPLET_IP=$CURRENT_DROPLET_IP" >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no circle@$CURRENT_DROPLET_IP bash -c '
            sudo cat ~/password.txt | docker login --username relovely --password-stdin;
            sudo docker stop $(docker ps -a -q);
            sudo docker rm -f $(docker ps -a -q);
            sudo docker rmi -f $(docker images -q);
            sudo docker pull relovely/relovely-api:latest;
            sudo docker run --env-file ~/env.config -d --network host relovely/relovely-api'
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop

